# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "upgrade"

[api]
enabled = true
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. `public` and `graphql_public` schemas are included by default.
schemas = ["public", "graphql_public"]
# Extra schemas to add to the search_path of every request.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 150

[api.tls]
# Enable HTTPS endpoints locally using a self-signed certificate.
enabled = false

[db]
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# Run `SHOW server_version;` on the remote database to check.
major_version = 17

# local connection pooler.
[db.pooler]
enabled = false

[db.migrations]
# Specifies an ordered list of schema files that describe your database.
# Supports glob patterns relative to supabase directory: "./schemas/*.sql"
schema_paths = ["./migrations/*.sql"]

[db.seed]
# If enabled, seeds the database after migrations during a db reset.
enabled = true
# Specifies an ordered list of seed files to load during db reset.
# Supports glob patterns relative to supabase directory: "./seeds/*.sql"
sql_paths = ["./seeds/*.sql"]

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: IPv4)
ip_version = "IPv6"
# The maximum length in bytes of HTTP request headers. (default: 4096)
# max_header_length = 4096

# Experimental features may be deprecated any time
[experimental]
# Configures Postgres storage engine to use OrioleDB (S3)
orioledb_version = "17.0.1.087"
# Configures S3 bucket URL, eg. <bucket_name>.s3-<region>.amazonaws.com
# s3_host = "env(S3_HOST)"
# Configures S3 bucket region, eg. us-east-1
# s3_region = "env(S3_REGION)"
# Configures AWS_ACCESS_KEY_ID for S3 bucket
# s3_access_key = "env(S3_ACCESS_KEY)"
# Configures AWS_SECRET_ACCESS_KEY for S3 bucket
# s3_secret_key = "env(S3_SECRET_KEY)"

[studio]
enabled = false
[storage]
enabled = false
[auth]
enabled = true
enable_signup = false
additional_redirect_urls = []
[auth.email]
enable_signup = false
[auth.sms]
enable_signup = false
[auth.sms.twilio]
enabled = false
[auth.mfa.totp]
enroll_enabled = false
verify_enabled = false
[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false
[edge_runtime]
enabled = false
[analytics]
enabled = false
