name: ci&cd

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: depot-ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - parallel:
          - name: build
            run: node --run build
          - name: lint
            run: node --run lint
          - name: typecheck
            run: node --run typecheck

  docker-push:
    #if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ci]
    runs-on: depot-ubuntu-24.04
    environment: image-registry
    permissions:
      contents: read

    steps:
      - uses: depot/setup-action@15c09a5f77a0840ad4bce955686522a257853461 # v1.7.1

      - name: Build and maybe Push Docker image
        uses: depot/build-push-action@98e78adca7817480b8185f474a400b451d74e287 # v1.18.0
        with:
          project: z3q9sj669s
          platforms: linux/amd64
          save: true
          save-tags: |
            latest
            ${{ github.sha }}
