/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown
      }
    }
  }
  "/patches": {
    get: {
      parameters: {
        query: {
          /** The patch ID, e.g. `7.00`, `7.28c`, `7.29` */
          id?: parameters["rowFilter.patches.id"]
          links?: parameters["rowFilter.patches.links"]
          releasedAt?: parameters["rowFilter.patches.releasedAt"]
          number?: parameters["rowFilter.patches.number"]
          /** Filtering Columns */
          select?: parameters["select"]
          /** Ordering */
          order?: parameters["order"]
          /** Limiting and Pagination */
          offset?: parameters["offset"]
          /** Limiting and Pagination */
          limit?: parameters["limit"]
        }
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"]
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"]
          /** Preference */
          Prefer?: parameters["preferCount"]
        }
      }
      responses: {
        /** OK */
        200: {
          schema: definitions["patches"][]
        }
        /** Partial Content */
        206: unknown
      }
    }
    post: {
      parameters: {
        body: {
          /** patches */
          patches?: definitions["patches"]
        }
        query: {
          /** Filtering Columns */
          select?: parameters["select"]
        }
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"]
        }
      }
      responses: {
        /** Created */
        201: unknown
      }
    }
    delete: {
      parameters: {
        query: {
          /** The patch ID, e.g. `7.00`, `7.28c`, `7.29` */
          id?: parameters["rowFilter.patches.id"]
          links?: parameters["rowFilter.patches.links"]
          releasedAt?: parameters["rowFilter.patches.releasedAt"]
          number?: parameters["rowFilter.patches.number"]
        }
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"]
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
    patch: {
      parameters: {
        query: {
          /** The patch ID, e.g. `7.00`, `7.28c`, `7.29` */
          id?: parameters["rowFilter.patches.id"]
          links?: parameters["rowFilter.patches.links"]
          releasedAt?: parameters["rowFilter.patches.releasedAt"]
          number?: parameters["rowFilter.patches.number"]
        }
        body: {
          /** patches */
          patches?: definitions["patches"]
        }
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"]
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
  }
  "/subscriptions": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.subscriptions.id"]
          endpoint?: parameters["rowFilter.subscriptions.endpoint"]
          createdAt?: parameters["rowFilter.subscriptions.createdAt"]
          auth?: parameters["rowFilter.subscriptions.auth"]
          p256dh?: parameters["rowFilter.subscriptions.p256dh"]
          environment?: parameters["rowFilter.subscriptions.environment"]
          /** Filtering Columns */
          select?: parameters["select"]
          /** Ordering */
          order?: parameters["order"]
          /** Limiting and Pagination */
          offset?: parameters["offset"]
          /** Limiting and Pagination */
          limit?: parameters["limit"]
        }
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"]
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"]
          /** Preference */
          Prefer?: parameters["preferCount"]
        }
      }
      responses: {
        /** OK */
        200: {
          schema: definitions["subscriptions"][]
        }
        /** Partial Content */
        206: unknown
      }
    }
    post: {
      parameters: {
        body: {
          /** subscriptions */
          subscriptions?: definitions["subscriptions"]
        }
        query: {
          /** Filtering Columns */
          select?: parameters["select"]
        }
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"]
        }
      }
      responses: {
        /** Created */
        201: unknown
      }
    }
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.subscriptions.id"]
          endpoint?: parameters["rowFilter.subscriptions.endpoint"]
          createdAt?: parameters["rowFilter.subscriptions.createdAt"]
          auth?: parameters["rowFilter.subscriptions.auth"]
          p256dh?: parameters["rowFilter.subscriptions.p256dh"]
          environment?: parameters["rowFilter.subscriptions.environment"]
        }
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"]
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.subscriptions.id"]
          endpoint?: parameters["rowFilter.subscriptions.endpoint"]
          createdAt?: parameters["rowFilter.subscriptions.createdAt"]
          auth?: parameters["rowFilter.subscriptions.auth"]
          p256dh?: parameters["rowFilter.subscriptions.p256dh"]
          environment?: parameters["rowFilter.subscriptions.environment"]
        }
        body: {
          /** subscriptions */
          subscriptions?: definitions["subscriptions"]
        }
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"]
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
  }
}

export interface definitions {
  patches: {
    /**
     * The patch ID, e.g. `7.00`, `7.28c`, `7.29`
     *
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string
    links: string[]
    releasedAt?: string
    number: number
  }
  /** Web Push Notifications subscription data */
  subscriptions: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string
    endpoint: string
    createdAt: string
    auth: string
    p256dh: string
    environment: string
  }
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object"
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none"
  /** Preference */
  preferCount: "count=none"
  /** Filtering Columns */
  select: string
  /** On Conflict */
  on_conflict: string
  /** Ordering */
  order: string
  /** Limiting and Pagination */
  range: string
  /** Limiting and Pagination */
  rangeUnit: string
  /** Limiting and Pagination */
  offset: string
  /** Limiting and Pagination */
  limit: string
  /** patches */
  "body.patches": definitions["patches"]
  /** The patch ID, e.g. `7.00`, `7.28c`, `7.29` */
  "rowFilter.patches.id": string
  "rowFilter.patches.links": string
  "rowFilter.patches.releasedAt": string
  "rowFilter.patches.number": string
  /** subscriptions */
  "body.subscriptions": definitions["subscriptions"]
  "rowFilter.subscriptions.id": string
  "rowFilter.subscriptions.endpoint": string
  "rowFilter.subscriptions.createdAt": string
  "rowFilter.subscriptions.auth": string
  "rowFilter.subscriptions.p256dh": string
  "rowFilter.subscriptions.environment": string
}

export interface operations {}
