name: CI/CD
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/CICD.yml"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/CICD.yml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.7.3
        with:
          useRollingCache: true
          install-command: yarn install --immutable

      - run: yarn lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.7.3
        with:
          useRollingCache: true
          install-command: yarn install --immutable

      - run: yarn build
